
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 30 22:36:32 CEST 2022
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int EGALITE = 16;
  public static final int RETOURNE = 12;
  public static final int IDF = 20;
  public static final int CSTBOOLEENNE = 22;
  public static final int EGAL = 9;
  public static final int CSTENTIERE = 21;
  public static final int INFERIEUR = 15;
  public static final int ECRIRE = 8;
  public static final int FONCTION = 5;
  public static final int DIFFERENT = 17;
  public static final int VIRGULE = 7;
  public static final int PAR_FERMANTE = 11;
  public static final int POINTVIRGULE = 6;
  public static final int VARIABLES = 4;
  public static final int ENTIER = 23;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 14;
  public static final int UNION = 19;
  public static final int error = 1;
  public static final int INTERSECTION = 18;
  public static final int BOOLEEN = 24;
  public static final int DEBUT = 2;
  public static final int ADDITION = 13;
  public static final int FIN = 3;
  public static final int PAR_OUVRANTE = 10;
}

