
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 29 11:00:54 CET 2022
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 5;
  public static final int IDF = 11;
  public static final int DEBUT = 2;
  public static final int POINTVIRGULE = 4;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int EGAL = 9;
  public static final int LIRE = 6;
  public static final int ENTIER = 7;
  public static final int error = 1;
  public static final int CSTENTIERE = 10;
  public static final int BOOLEEN = 8;
}

