
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 15 20:51:39 CET 2022
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 12;
  public static final int DEBUT = 2;
  public static final int POINTVIRGULE = 5;
  public static final int TRUE = 9;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int VARIABLES = 4;
  public static final int EGAL = 10;
  public static final int ENTIER = 7;
  public static final int error = 1;
  public static final int CSTENTIERE = 11;
  public static final int BOOLEEN = 8;
}

